/// Flutter icons PlanalistIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlanalistIcon
///      fonts:
///       - asset: fonts/PlanalistIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PlanalistIcon {
  PlanalistIcon._();

  static const _kFontFam = 'PlanalistIcon';
  static const String _kFontPkg = null;

  static const IconData account = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData watering = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chart = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData setting = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData play = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData help = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam);
}
